export const CATEGORIES_ACTION_TYPES = {
  FETCH_CETEGORIES_START: 'category/FETCH_CETEGORIES_START',
  FETCH_CETEGORIES_SUCCESS: 'category/FETCH_CETEGORIES_SUCCESS',
  FETCH_CETEGORIES_FAILED: 'category/FETCH_CETEGORIES_FAILED',
}